### ISSUE TITLE
Future 65816 support (Apple IIgs, SNES)

### ISSUE THREAD

**Issue by Hamtaro126** [michaelcmartin/Ophis#18]
Hello, I've wondered if someone can add 65816 (16-bit) support in the future as it has great stuff!

Otherwise, Seems Complete!

**Comment by michaelcmartin** [comment]
Having finally gotten around to learning enough 65816 to see how it is used in the Apple IIgs and SNES, I don't think it's actually a good fit for Ophis.  Most traditional syntaxes use symbols (^, []) that conflict with Ophis's own use of them, and these would vastly complicate the parser to the point that it would effectively be a new application.

Added to this, the IIgs needs special linking work to produce its final binaries, and Ophis's memory model is a poor fit for this.

For future readers who come to this ticket looking to do 65816 development, "Merlin 32" is an excellent tool for creating fully-fledged Apple IIgs applications and either "WLA-DX" or the "ca65" and "ld65" tools from the cc65 suite for SNES work.
