### ISSUE TITLE
no listing if errors in assembly ?

### ISSUE THREAD

**Issue by mstram** [michaelcmartin/Ophis#28]
I'm running ophis ver 2.1 on XP.

It seems a listing is only produced if there are no errors in the assembly?

Is this by design ?

**Comment by michaelcmartin** [comment]
I wouldn't say it's *by design* but the listing output does need at least some of the output to have succeeded. It can't list bytecode values for a label which was never defined, for instance, and that has an impact on the opcode and labels too.
